### ISSUE TITLE
Delete Event not possible

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#1399]
ERROR:open_event:Exception on /events/45/delete/ [GET]
2016-07-03T21:13:07.738906+00:00 app[web.1]: Traceback (most recent call last):
2016-07-03T21:13:07.738907+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2016-07-03T21:13:07.738897+00:00 app[web.1]:     exc_info
2016-07-03T21:13:07.738898+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
2016-07-03T21:13:07.738898+00:00 app[web.1]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
2016-07-03T21:13:07.738898+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
2016-07-03T21:13:07.738907+00:00 app[web.1]:     response = self.full_dispatch_request()
2016-07-03T21:13:07.738908+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2016-07-03T21:13:07.738908+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2016-07-03T21:13:07.738908+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask_restplus/api.py", line 536, in error_router
2016-07-03T21:13:07.738909+00:00 app[web.1]:     return original_handler(e)
2016-07-03T21:13:07.738909+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
2016-07-03T21:13:07.738909+00:00 app[web.1]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
2016-07-03T21:13:07.738910+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2016-07-03T21:13:07.738910+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2016-07-03T21:13:07.738910+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2016-07-03T21:13:07.738911+00:00 app[web.1]:     rv = self.dispatch_request()
2016-07-03T21:13:07.738911+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2016-07-03T21:13:07.738912+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2016-07-03T21:13:07.738912+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
2016-07-03T21:13:07.738912+00:00 app[web.1]:     return self._run_view(f, *args, **kwargs)
2016-07-03T21:13:07.738913+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask_admin/base.py", line 367, in _run_view
2016-07-03T21:13:07.738913+00:00 app[web.1]:     return fn(self, *args, **kwargs)
2016-07-03T21:13:07.738914+00:00 app[web.1]:   File "/app/open_event/helpers/permission_decorators.py", line 20, in decorated_function
2016-07-03T21:13:07.738914+00:00 app[web.1]:     return f(*args, **kwargs)
2016-07-03T21:13:07.738914+00:00 app[web.1]:   File "/app/open_event/views/admin/models_views/events.py", line 242, in delete_view
2016-07-03T21:13:07.738915+00:00 app[web.1]:     event = DataManager.delete_event(event_id)
2016-07-03T21:13:07.738915+00:00 app[web.1]:   File "/app/open_event/helpers/data.py", line 1082, in delete_event
2016-07-03T21:13:07.738916+00:00 app[web.1]:     Track.query.filter_by(id=e_id).delete()
2016-07-03T21:13:07.738916+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3073, in delete
2016-07-03T21:13:07.738916+00:00 app[web.1]:     delete_op.exec_()
2016-07-03T21:13:07.738917+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1127, in exec_
2016-07-03T21:13:07.738917+00:00 app[web.1]:     self._do_exec()
2016-07-03T21:13:07.738917+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1311, in _do_exec
2016-07-03T21:13:07.738918+00:00 app[web.1]:     mapper=self.mapper)
2016-07-03T21:13:07.738918+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1034, in execute
2016-07-03T21:13:07.738918+00:00 app[web.1]:     bind, close_with_result=True).execute(clause, params or {})
2016-07-03T21:13:07.738919+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
2016-07-03T21:13:07.738922+00:00 app[web.1]:     return meth(self, multiparams, params)
2016-07-03T21:13:07.738893+00:00 app[web.1]:     return meth(self, multiparams, params)
2016-07-03T21:13:07.738923+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
2016-07-03T21:13:07.738923+00:00 app[web.1]:     return connection._execute_clauseelement(self, multiparams, params)
2016-07-03T21:13:07.738923+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
2016-07-03T21:13:07.738924+00:00 app[web.1]:     compiled_sql, distilled_params
2016-07-03T21:13:07.738924+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
2016-07-03T21:13:07.738925+00:00 app[web.1]:     context)
2016-07-03T21:13:07.738925+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
2016-07-03T21:13:07.738925+00:00 app[web.1]:     exc_info
2016-07-03T21:13:07.738926+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
2016-07-03T21:13:07.738926+00:00 app[web.1]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
2016-07-03T21:13:07.738926+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
2016-07-03T21:13:07.738927+00:00 app[web.1]:     context)
2016-07-03T21:13:07.738927+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
2016-07-03T21:13:07.738927+00:00 app[web.1]:     cursor.execute(statement, parameters)
2016-07-03T21:13:07.738928+00:00 app[web.1]: IntegrityError: (psycopg2.IntegrityError) update or delete on table "tracks" violates foreign key constraint "session_track_id_fkey" on table "session"
2016-07-03T21:13:07.738928+00:00 app[web.1]: DETAIL:  Key (id)=(45) is still referenced from table "session".

**Comment by SaptakS** [comment]
Can you tell me how to recreate the error?

**Comment by rafalkowalski** [comment]
go to http://open-event.herokuapp.com/admin/events/ remove event
