### ISSUE TITLE
Run import/export events as background tasks using Celery (& Redis)

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#1500]
Parent issue: #1449 

Importing/Exporting of events can take a large amount of time. So it is not a good idea to block the application's main thread while importing/exporting an event.
We can use Celery for running these tasks in the background. Celery requires Redis which is available as REDISTOGO extension on Heroku. Locally redis can be setup from http://redis.io/download 

Celery http://www.celeryproject.org
Redis http://redis.io/

**Comment by niranjan94** [comment]
```
2016-07-11T06:17:06.319448+00:00 app[web.1]: [2016-07-11 06:17:06,319: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
2016-07-11T06:17:06.319478+00:00 app[web.1]: Traceback (most recent call last):
2016-07-11T06:17:06.319480+00:00 app[web.1]:     blueprint.start(self)
2016-07-11T06:17:06.319481+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
2016-07-11T06:17:06.319485+00:00 app[web.1]:     chan = self.transport.create_channel(self.connection)
2016-07-11T06:17:06.319488+00:00 app[web.1]:     self._disconnect_pools()
2016-07-11T06:17:06.319489+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/redis.py", line 484, in _disconnect_pools
2016-07-11T06:17:06.319499+00:00 app[web.1]: ConnectionError
2016-07-11T06:17:07.393182+00:00 app[web.1]: [2016-07-11 06:17:07,392: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
2016-07-11T06:17:07.393193+00:00 app[web.1]: Traceback (most recent call last):
2016-07-11T06:17:07.393194+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/celery/worker/consumer.py", line 279, in start
2016-07-11T06:17:07.393195+00:00 app[web.1]:     blueprint.start(self)
2016-07-11T06:17:07.393196+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
2016-07-11T06:17:07.393197+00:00 app[web.1]:     step.start(parent)
2016-07-11T06:17:07.393198+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/celery/worker/pidbox.py", line 46, in start
2016-07-11T06:17:07.393198+00:00 app[web.1]:     self.node.channel = c.connection.channel()
2016-07-11T06:17:07.393199+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/connection.py", line 242, in channel
2016-07-11T06:17:07.393200+00:00 app[web.1]:     chan = self.transport.create_channel(self.connection)
2016-07-11T06:17:07.393201+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 791, in create_channel
2016-07-11T06:17:07.393202+00:00 app[web.1]:     channel = self.Channel(connection)
2016-07-11T06:17:07.393202+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/redis.py", line 466, in __init__
2016-07-11T06:17:07.393205+00:00 app[web.1]:     self._async_pool.disconnect()
2016-07-11T06:17:07.393206+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 898, in disconnect
2016-07-11T06:17:07.393206+00:00 app[web.1]:     connection.disconnect()
2016-07-11T06:17:07.393207+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/redis.py", line 854, in disconnect
2016-07-11T06:17:07.393208+00:00 app[web.1]:     channel._on_connection_disconnect(self)
2016-07-11T06:17:07.393209+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/redis.py", line 498, in _on_connection_disconnect
2016-07-11T06:17:07.393209+00:00 app[web.1]:     raise get_redis_ConnectionError()
2016-07-11T06:17:07.393210+00:00 app[web.1]: ConnectionError
```

**Comment by niranjan94** [comment]
The redistogo url is properly set in the environment variable

**Comment by aviaryan** [comment]
@niranjan94 Shifted to heroku-redis in #1553 and now it is working.

**Comment by mariobehling** [comment]
@aviaryan It is all a good idea, but I see that you put out a lightbox window while you generate the export and therefore the user has to wait until it is finished?

I do not think this is a good solution.

Please propose a better solution, e.g. we can have a progress bar in the event table somewhere and when it is finished there is a download link. In the meantime the user can also go to other pages and check later, if the download has finished. 

Where is the best place to have this progress bar and download link in the table?

**Comment by aviaryan** [comment]
@mariobehling 
Opened issue #1758 as a follow-up issue for that.

**Comment by aviaryan** [comment]
Import/Export now run as Celery tasks. As far as using a different way to show progress in these tasks is concerned, #1758 has been opened for that. So closing this.
