### ISSUE TITLE
[Help Request] Trouble connecting to postgres inside vagrant

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#190]
I was following the instructions to setup server in vagrant. After ssh-ing into the box, everything went well until `python create_db.py` which threw an error, 

    password authentication failed for user "open_event_user"

The `DATABASE_URL` was set. I tried to manually log in to postgres but it still showed the same error. The password is set to the default provided for testing, `start`.

Here's a detailed log of the same after I entered the command.

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python create_db.py 
Traceback (most recent call last):
  File "create_db.py", line 6, in <module>
    db.create_all()
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 895, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 887, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 3695, in create_all
    tables=tables)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1855, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1848, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1060, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "open_event_user"
FATAL:  password authentication failed for user "open_event_user"
```

Any help would be appreciated.

**Comment by aditya1702** [comment]
@shivamMg  have you tried reinstalling the packages?

**Comment by shivamMg** [comment]
@aditya1702 I removed and reinstalled the packages, both the ones specified for apt-get in `install.sh` and the ones in `requirements.txt`, but it still gives the same error.

**Comment by aditya1702** [comment]
@shivamMg I think the code is correct. The problem is with the password. Look at these links, they may help
https://github.com/cms-dev/cms/issues/60
http://stackoverflow.com/questions/5963739/got-an-error-while-connecting-to-database

**Comment by shivamMg** [comment]
Thanks @aditya1702, I got it running. Turns out some commands in install.sh didn't execute, so the tables were never created. It's working now. :)

**Comment by rohanagarwal94** [comment]
@shivamMg could you be elaborate on how actually you managed to solve this? I am facing a similar issue.

**Comment by shivamMg** [comment]
@rohanagarwal94 IIRC it was because something went wrong when I was first installing (using install.sh) inside vagrant. And when I was trying again, the script exited because vm provisioning had already been done (https://github.com/fossasia/open-event-orga-server/blob/development/scripts/install.sh#L57). To make it work I just removed the exit statement.
