### ISSUE TITLE
Application crash - UndefinedError: 'event_id' is undefined

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-orga-server#237]
The following pages crash (as far as I have seen)
* http://localhost:5000/admin/
* http://localhost:5000/admin/event/

The output of the HTML page -

> Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

The stack-trace - 
```
Exception on /admin/event/ [GET]
Traceback (most recent call last):
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/flask_admin/base.py", line 354, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/aviaryan/Documents/github/open-event-orga-server/open_event/views/admin/models_views/event.py", line 79, in index_view
    return super(EventView, self).index_view()
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/flask_admin/base.py", line 354, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/flask_admin/model/base.py", line 1466, in index_view
    return_url=self._get_list_url(view_args),
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/flask_admin/base.py", line 294, in render
    return render_template(template, **kwargs)
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aviaryan/Documents/github/open-event-orga-server/open_event/templates/admin/model/list.html", line 5, in top-level template code
    {% import 'admin/actions.html' as actionlib with context %}
  File "/home/aviaryan/Documents/github/open-event-orga-server/open_event/templates/admin/base1.html", line 32, in top-level template code
    {{ menu1.render_menu() }}
  File "/home/aviaryan/Documents/github/open-event-orga-server/open_event/templates/admin/menu.html", line 17, in template
    {% block main_menu %}
  File "/home/aviaryan/Documents/github/open-event-orga-server/open_event/templates/admin/menu.html", line 36, in block "main_menu"
    <li {% if event.id == event_id|int() %}class="active"{% endif %}>
  File "/home/aviaryan/anaconda2/lib/python2.7/site-packages/jinja2/filters.py", line 527, in do_int
    return int(float(value))
UndefinedError: 'event_id' is undefined
127.0.0.1 - - [06/Apr/2016 23:54:12] "GET /admin/event/ HTTP/1.1" 500 -
```

**Comment by aviaryan** [comment]
Opened Pull request #238
