### ISSUE TITLE
Gunicorn error: 'Response' object has no attribute 'status_code'

### ISSUE THREAD

**Issue by hongquan** [fossasia/open-event-orga-server#2455]
I followed the _INSTALLATION_LOCAL.md_ doc. I ran the web app with this command:

```
INTEGRATE_SOCKETIO=true gunicorn app:app -k eventlet -b localhost:5000
```

After testing a while, I got this error in console:

```
[2016-10-07 10:27:43 +0000] [23475] [ERROR] Error handling request /socket.io/?EIO=3&transport=websocket&sid=a5d16c6d35624ad1a57b8d0b957e6831
Traceback (most recent call last):
  File "/home/quan/Works/Envs/oevent/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/quan/Works/Envs/oevent/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 112, in handle_request
    resp.close()
  File "/home/quan/Works/Envs/oevent/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 418, in close
    self.send_headers()
  File "/home/quan/Works/Envs/oevent/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 334, in send_headers
    tosend = self.default_headers()
  File "/home/quan/Works/Envs/oevent/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 315, in default_headers
    elif self.should_close():
  File "/home/quan/Works/Envs/oevent/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 238, in should_close
    if self.status_code < 200 or self.status_code in (204, 304):
AttributeError: 'Response' object has no attribute 'status_code'
```

Update:
- My Python env: http://hastebin.com/nuwawupalu.ini

**Comment by aviaryan** [comment]
It is a gunicorn issue (https://github.com/miguelgrinberg/Flask-SocketIO/issues/223#issuecomment-179957484) and it doesn't lead to any data loss or problems. (https://github.com/miguelgrinberg/Flask-SocketIO/issues/223#issuecomment-222026743) 
I don't think there is any thing we can do here. You can check the open issue on gunicorn. https://github.com/benoitc/gunicorn/issues/1210
