### ISSUE TITLE
create event issue

### ISSUE THREAD

**Issue by darkharshg** [fossasia/open-event-orga-server#3021]
I followed in installation procedures in [Local.md](https://github.com/fossasia/open-event-orga-server/blob/development/docs/installation/local.md) but whenever I try to create an event it lands me onto the following page.
![foss](https://cloud.githubusercontent.com/assets/22577945/22181223/564a9a08-e0ad-11e6-9d46-586b43bdde03.png)

Is there anyway to resolve this?

**Comment by SaptakS** [comment]
Can you provide the terminal log?

**Comment by darkharshg** [comment]
```
ERROR in app: Exception on /events/create/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 536, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nitin/Desktop/open-event-orga-server/app/views/users/events.py", line 91, in create_view
    current_timezone = get_current_timezone()
  File "/home/nitin/Desktop/open-event-orga-server/app/helpers/wizard/helpers.py", line 17, in get_current_timezone
    match = geolite2.lookup(get_real_ip(True) or '127.0.0.1')
  File "/usr/local/lib/python2.7/dist-packages/geoip.py", line 364, in lookup
    return self._get_actual_db().lookup(ip_addr)
  File "/usr/local/lib/python2.7/dist-packages/geoip.py", line 204, in lookup
    return self._lookup(ip_addr)
  File "/usr/local/lib/python2.7/dist-packages/geoip.py", line 249, in _lookup
    packed_addr = pack_ip(ip_addr)
  File "/usr/local/lib/python2.7/dist-packages/geoip.py", line 37, in pack_ip
    raise ValueError('Malformed IP address')
ValueError: Malformed IP address

```

**Comment by darkharshg** [comment]
```
ERROR in app: Exception on /events/create/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 536, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/harsh/Desktop/open-event-orga-server/app/views/users/events.py", line 91, in create_view
    current_timezone = get_current_timezone()
  File "/home/harsh/Desktop/open-event-orga-server/app/helpers/wizard/helpers.py", line 17, in get_current_timezone
    match = geolite2.lookup(get_real_ip(True) or '127.0.0.1')
  File "/usr/local/lib/python2.7/dist-packages/geoip.py", line 364, in lookup
    return self._get_actual_db().lookup(ip_addr)
  File "/usr/local/lib/python2.7/dist-packages/geoip.py", line 204, in lookup
    return self._lookup(ip_addr)
  File "/usr/local/lib/python2.7/dist-packages/geoip.py", line 249, in _lookup
    packed_addr = pack_ip(ip_addr)
  File "/usr/local/lib/python2.7/dist-packages/geoip.py", line 37, in pack_ip
    raise ValueError('Malformed IP address')
ValueError: Malformed IP address

```

**Comment by aviaryan** [comment]
@darkharshg Can you try accessing the server from `127.0.0.1:5000` rather than localhost:5000. 
I think it is worth a shot. 👍

**Comment by darkharshg** [comment]
@aviaryan using 127.0.0.1 instead of localhost lands me on 404 page.

**Comment by aviaryan** [comment]
I ran the latest dev version on my side without any issues. Does this error happen only in create event page or in other pages too? Also which OS are you on?

**Comment by darkharshg** [comment]
@aviaryan yes it happens only on create event page. Everything else works just fine. I'm working on ubuntu 14.04

**Comment by Himanshi-Khandelwal** [comment]
@darkharshg try it using without internet , it will work . it's geoip problem
