### ISSUE TITLE
Register as speaker: 500 Server error

### ISSUE THREAD

**Issue by roschaefer** [fossasia/open-event-orga-server#3565]
I did the following twice (with a googlemail address and an ordinary email address):
1) Click on https://eventyay.com/e/5642d9a1/cfs/
2) Create an account
3) Register as speaker
4) Fill in all requested form fields
5) Hit save

The next time when I want to visit https://eventyay.com/e/5642d9a1/cfs/ I get a 500 HTTP error.
![internal server error - 500 - eventyay - chromium_138](https://cloud.githubusercontent.com/assets/2110676/25659318/7e14c8a2-3007-11e7-8d08-c848ecb8a7d5.png)

On the first time, I noticed a small green message: "You have been registered as Speaker". However the 500 error showed up below. Whenever I try to access https://eventyay.com/e/5642d9a1/cfs/ I get the same error again. It effectively prevents me from registering as speaker :clap:

**Comment by poush** [comment]
This happens when I try to register as speaker without proposing any session. Since no session is mapped with my speaker request.

**Comment by LuD1161** [comment]
@poush 
Same issue I am facing right now.

![error-registering-user](https://cloud.githubusercontent.com/assets/17861054/25772340/3cd3c646-3286-11e7-9c66-dfc2a445b8cd.png)
```
Exception on /e/a2cd477e/cfs/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 557, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/open-event-orga-server/app/views/public/event_detail.py", line 266, in display_event_cfs
    existing_sessions=existing_sessions)
  File "/usr/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/open-event-orga-server/app/templates/gentelella/guest/event/cfs.html", line 5, in top-level template code
    {% set scrollspy_top = (carousel_height + 95) ~ "px" %}
  File "/root/open-event-orga-server/app/templates/gentelella/guest/event/base.html", line 21, in top-level template code
    {% set event_image = url_for("static", filename="placeholders/" + placeholder_images["Other"], _external=True) %}
  File "/root/open-event-orga-server/app/templates/gentelella/base.html", line 56, in top-level template code
    {% block body %}
  File "/root/open-event-orga-server/app/templates/gentelella/guest/event/base.html", line 182, in block "body"
    {% block content %}
  File "/root/open-event-orga-server/app/templates/gentelella/guest/event/cfs.html", line 103, in block "content"
    <a href="{{ url_for('my_sessions.process_speaker_view',speaker=user_speaker[0]['id']) }}" type="button" class="btn btn-info" id = "speaker-button">{{ _("Edit Speaker Details") }}</a>
  File "/usr/lib/python2.7/dist-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'my_sessions.process_speaker_view' with values ['speaker']. Did you forget to specify values ['speaker_id']?

```

**Comment by LuD1161** [comment]
@roschaefer @poush 
Not only for speaker's but also when registering for the sessions , I get the same error.

![image](https://cloud.githubusercontent.com/assets/17861054/25772397/9990417e-3287-11e7-80c5-0f5554ef8ee3.png)
```
Exception on /e/a2cd477e/cfs/new_session/ [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 557, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/open-event-orga-server/app/views/public/event_detail.py", line 433, in process_event_cfs_session
    DataManager.add_session_to_event(request, event.id)
  File "/root/open-event-orga-server/app/helpers/data.py", line 260, in add_session_to_event
    trigger_new_session_notifications(new_session.id, event=event)
  File "/root/open-event-orga-server/app/helpers/notification_email_triggers.py", line 17, in trigger_new_session_notifications
    event_id=event.id, session_id=session_id, _external=True)
  File "/usr/lib/python2.7/dist-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'event_sessions.session_display_view' with values ['event_id']. Did you forget to specify values ['session_id']?
```

**Comment by poush** [comment]
Strange, I am able to propose session with no issues. I will re-try to produce this error.

**Comment by roschaefer** [comment]
@poush could you please re-open this?

I did the following: 
1. visit https://eventyay.com/e/5642d9a1/cfs/
2. Click on "Submit proposal"
3. Log-in with my email and password
4. HTTP 500 error

![internal server error - 500 - eventyay - chromium_140](https://cloud.githubusercontent.com/assets/2110676/25773455/bf52cecc-327d-11e7-875e-06d1c6f24b82.png)

Still can't submit my talk :sob:

**Comment by shubham-padia** [comment]
@roschaefer The changes are still on development branch and not merged to master, maybe @SaptakS or @niranjan94 could help.

**Comment by niranjan94** [comment]
@shubham-padia @roschaefer will trigger a production deployment now. You should see the changes in about 40 mins.

**Comment by roschaefer** [comment]
Sucess! thanks :smile_cat:

**Comment by niranjan94** [comment]
@roschaefer you're welcome ! 😄 
Apologies for the inconvenience ..
