### ISSUE TITLE
NoResultFound: No row was found for one()

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-orga-server#4467]
https://sentry.eventyay.com/eventyay/dev-api/issues/96/

```
NoResultFound: No row was found for one()
(16 additional frame(s) were not displayed)
...
  File "app/api/helpers/permission_manager.py", line 436, in permission_manager
    return permissions[args[0]](view, view_args, view_kwargs, *args, **kwargs)
  File "app/api/helpers/permission_manager.py", line 286, in create_event
    return view(*view_args, **view_kwargs)
  File "app/api/schema/events.py", line 23, in validate_date
    event = Event.query.filter_by(id=original_data['data']['id']).one()

NoResultFound: No row was found for one()
```

**Comment by vaibhavsingh97** [comment]
Can i take up this issue?

**Comment by shubham-padia** [comment]
@vaibhavsingh97 Have you setup the nextgen branch locally? If you've setup the nextgen branch locally, please go ahead.

**Comment by vaibhavsingh97** [comment]
@shubham-padia I am trying to setup but faiing while installing requirements from `requirement.txt`.
```
Collecting librabbitmq==1.5.1 (from -r requirements/common.txt (line 24))
  Using cached librabbitmq-1.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4xlg7rh9/librabbitmq/setup.py", line 199
        except Exception, exc:
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4xlg7rh9/librabbitmq/
```
I tried all the possible way, i failed 😞 
OS: Arch Linux
`Linux deathping 4.12.12-1-ARCH #1 SMP PREEMPT Sun Sep 10 09:41:14 CEST 2017 x86_64 GNU/Linux`

**Comment by shubham-padia** [comment]
The project uses python2, please make sure you're not using python 3. Use `pip2` instead of `pip`.

**Comment by vaibhavsingh97** [comment]
@shubham-padia How to reproduce? Please guide

**Comment by invinciblycool** [comment]
Oh! I just noticed that you were about to push a PR @rahuldecoded .
I am extremely sorry.
:disappointed:

**Comment by rahuldecoded** [comment]
@invinciblycool No problem.
