### ISSUE TITLE
error while deploying locally

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#71]
```
OperationalError: (sqlite3.OperationalError) no such table: events [SQL: u'SELECT events.id AS events_id, events.name AS events_name, events.email AS e
vents_email, events.color AS events_color, events.logo AS events_logo, events.start_time AS events_start_time, events.end_time AS events_end_time, even
ts.latitude AS events_latitude, events.longitude AS events_longitude, events.location_name AS events_location_name, events.slogan AS events_slogan, eve
nts.url AS events_url \nFROM events']
```
This is the error I get when deploying locally with `python run.py`

**Comment by rafalkowalski** [comment]
@championswimmer did you create a database via python console?

execute this code:

"""from open_event import app
from open_event.models import db


with app.app_context():
	db.drop_all()

with app.app_context():
	db.create_all()"""

**Comment by rafalkowalski** [comment]
@championswimmer Could you tell me whether above commands helps?

**Comment by championswimmer** [comment]
Hi I was updating latest code and deploying to DigitalOcean (springboard.championswimmer.in) 

and I faced this error

```
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from open_event import app
  File "/home/championswimmer/web/open-event-orga-server/open_event/__init__.py", line 25, in <module>
    app.config.from_object('config.ProductionConfig')
  File "/usr/local/lib/python2.7/dist-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 412, in import_string
    __import__(import_name)
  File "/home/championswimmer/web/open-event-orga-server/config.py", line 13, in <module>
    class ProductionConfig(Config):
  File "/home/championswimmer/web/open-event-orga-server/config.py", line 15, in ProductionConfig
    SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'DATABASE_URL'
```

**Comment by rafalkowalski** [comment]
@championswimmer Could you pull changes now?
